const data = [{ "name" : "StartSymbol", "children" : [{ "name" : "SourceFile", "children" : [{ "name" : "Package", "children" : [{ "name" : "package", "children" : []},
{ "name" : "main", "children" : []},
{ "name" : ";", "children" : []},
]},
{ "name" : "Imports", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "DeclarationList", "children" : [{ "name" : "", "children" : []},
{ "name" : "FunctionDeclaration", "children" : [{ "name" : "func", "children" : []},
{ "name" : "Empty GenericTypeList", "children" : []},
{ "name" : "FunctionHeader", "children" : [{ "name" : "main", "children" : []},
{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "Name", "children" : [{ "name" : "ix", "children" : []},
]},
{ "name" : "ArgumentType", "children" : [{ "name" : "int", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "y", "children" : []},
]},
]},
{ "name" : "ArgumentType", "children" : [{ "name" : "int", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "z", "children" : []},
]},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : ")", "children" : []},
{ "name" : "FunctionResult", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "FunctionBody", "children" : [{ "name" : "CompoundStatement", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "z", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "fg", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "adaf", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "gdsf", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "gsdfsdf", "children" : []},
]},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "z", "children" : []},
]},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "t", "children" : []},
]},
]},
{ "name" : "FunctionType", "children" : [{ "name" : "func", "children" : []},
{ "name" : "Empty GenericTypeList", "children" : []},
{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "x", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
{ "name" : "ArgumentType", "children" : [{ "name" : "y", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : ")", "children" : []},
{ "name" : "FunctionResult", "children" : [{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
]},
{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "t", "children" : []},
]},
]},
{ "name" : "GeneratorType", "children" : [{ "name" : "gen", "children" : []},
{ "name" : "Empty GenericTypeList", "children" : []},
{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "x", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
{ "name" : "ArgumentType", "children" : [{ "name" : "y", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : ")", "children" : []},
{ "name" : "FunctionResult", "children" : [{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "float", "children" : []},
]},
{ "name" : "PointerType", "children" : [{ "name" : "*", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
]},
{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "z", "children" : []},
]},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "ForHeader", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "0", "children" : []},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "+", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "1", "children" : []},
]},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "t", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "+", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "ForHeader", "children" : [{ "name" : "OSimpleStatement", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ";", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "ForHeader", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "1", "children" : []},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "ForHeader", "children" : [{ "name" : "OSimpleStatement", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ";", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "++", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "IfHeader", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "50", "children" : []},
]},
{ "name" : "*", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "99", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Name", "children" : [{ "name" : "t", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "FunctionDeclaration", "children" : [{ "name" : "func", "children" : []},
{ "name" : "Empty GenericTypeList", "children" : []},
{ "name" : "FunctionHeader", "children" : [{ "name" : "sec", "children" : []},
{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "int", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "x", "children" : []},
]},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : ")", "children" : []},
{ "name" : "FunctionResult", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "FunctionBody", "children" : [{ "name" : "CompoundStatement", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "x", "children" : []},
]},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
]},
]},
]},
][0];