const data = [{ "name" : "StartSymbol", "children" : [{ "name" : "SourceFile", "children" : [{ "name" : "Package", "children" : [{ "name" : "package", "children" : []},
{ "name" : "main", "children" : []},
{ "name" : ";", "children" : []},
]},
{ "name" : "Imports", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "DeclarationList", "children" : [{ "name" : "", "children" : []},
{ "name" : "FunctionDeclaration", "children" : [{ "name" : "func", "children" : []},
{ "name" : "Empty GenericTypeList", "children" : []},
{ "name" : "FunctionHeader", "children" : [{ "name" : "main", "children" : []},
{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
{ "name" : "FunctionResult", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "FunctionBody", "children" : [{ "name" : "CompoundStatement", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "z", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "fg", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "adaf", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "gdsf", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "gsdfsdf", "children" : []},
]},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "z", "children" : []},
]},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "Declaration Name", "children" : [{ "name" : "z", "children" : []},
]},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "ForHeader", "children" : [{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "0", "children" : []},
]},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "+", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "1", "children" : []},
]},
]},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "t", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "+", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "ForHeader", "children" : [{ "name" : "OSimpleStatement", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "ForHeader", "children" : [{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "1", "children" : []},
]},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "ForHeader", "children" : [{ "name" : "OSimpleStatement", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "100", "children" : []},
]},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "++", "children" : []},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "t", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "50", "children" : []},
]},
{ "name" : "*", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "99", "children" : []},
]},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Name", "children" : [{ "name" : "t", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "CommonDeclaration", "children" : [{ "name" : "const", "children" : []},
{ "name" : "ConstDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "16", "children" : []},
]},
]},
]},
]},
{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "a", "children" : []},
]},
]},
{ "name" : "OtherType", "children" : [{ "name" : "[", "children" : []},
{ "name" : "OExpression", "children" : [{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
{ "name" : "]", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "byte", "children" : []},
]},
]},
]},
]},
{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "p", "children" : []},
]},
]},
{ "name" : "OtherType", "children" : [{ "name" : "[", "children" : []},
{ "name" : "OExpression", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "]", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "byte", "children" : []},
]},
]},
]},
]},
{ "name" : "FunctionDeclaration", "children" : [{ "name" : "func", "children" : []},
{ "name" : "Empty GenericTypeList", "children" : []},
{ "name" : "FunctionHeader", "children" : [{ "name" : "f", "children" : []},
{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "ArgumentType", "children" : [{ "name" : "k", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : ")", "children" : []},
{ "name" : "FunctionResult", "children" : [{ "name" : "FunctionReturnType", "children" : [{ "name" : "Name", "children" : [{ "name" : "byte", "children" : []},
]},
]},
]},
]},
{ "name" : "FunctionBody", "children" : [{ "name" : "CompoundStatement", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "NonDeclarationStatement", "children" : [{ "name" : "return", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "byte", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "*", "children" : []},
{ "name" : "Literal", "children" : [{ "name" : "10007", "children" : []},
]},
]},
{ "name" : "%", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "FunctionDeclaration", "children" : [{ "name" : "func", "children" : []},
{ "name" : "Empty GenericTypeList", "children" : []},
{ "name" : "FunctionHeader", "children" : [{ "name" : "init", "children" : []},
{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
{ "name" : "FunctionResult", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "FunctionBody", "children" : [{ "name" : "CompoundStatement", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "p", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "make", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "OtherType", "children" : [{ "name" : "[", "children" : []},
{ "name" : "OExpression", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "]", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "byte", "children" : []},
]},
]},
{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "ForHeader", "children" : [{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "0", "children" : []},
]},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "<", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
]},
]},
{ "name" : ";", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "++", "children" : []},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "f", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "a", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "p", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "m", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "FunctionDeclaration", "children" : [{ "name" : "func", "children" : []},
{ "name" : "Empty GenericTypeList", "children" : []},
{ "name" : "FunctionHeader", "children" : [{ "name" : "main", "children" : []},
{ "name" : "(", "children" : []},
{ "name" : "OArgumentTypeListOComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
{ "name" : "FunctionResult", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "FunctionBody", "children" : [{ "name" : "CompoundStatement", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "CommonDeclaration", "children" : [{ "name" : "var", "children" : []},
{ "name" : "VarDeclaration", "children" : [{ "name" : "Declaration Name List", "children" : [{ "name" : "Declaration Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "Name", "children" : [{ "name" : "int", "children" : []},
]},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "0", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "RangeStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "range", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "a", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "a", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "f", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key array range\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "a", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "++", "children" : []},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key array size\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "0", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "RangeStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "range", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "p", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "p", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "f", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key pointer range\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "p", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "++", "children" : []},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key pointer size\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "0", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "RangeStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "range", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "m", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "m", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "f", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key map range\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "m", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "++", "children" : []},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key map size\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "0", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "RangeStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "range", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "a", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "f", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key:value array range\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "a", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "++", "children" : []},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key:value array size\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "0", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "RangeStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "range", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "p", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "f", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key:value pointer range\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "p", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "++", "children" : []},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key:value pointer size\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "=", "children" : []},
{ "name" : "Expression", "children" : [{ "name" : "Literal", "children" : [{ "name" : "0", "children" : []},
]},
]},
]},
{ "name" : "ForStatement", "children" : [{ "name" : "for", "children" : []},
{ "name" : "ForBody", "children" : [{ "name" : "RangeStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
]},
{ "name" : ":=", "children" : []},
{ "name" : "range", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "m", "children" : []},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "f", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key:value map range\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "v", "children" : []},
]},
{ "name" : "PrimaryExprNoParen", "children" : [{ "name" : "Name", "children" : [{ "name" : "m", "children" : []},
]},
{ "name" : "[", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "k", "children" : []},
]},
{ "name" : "]", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "++", "children" : []},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
{ "name" : "IfStatement", "children" : [{ "name" : "if", "children" : []},
{ "name" : "OSimpleStatement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "Expression", "children" : [{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
{ "name" : "!=", "children" : []},
{ "name" : "Name", "children" : [{ "name" : "size", "children" : []},
]},
]},
]},
]},
{ "name" : "LoopBody", "children" : [{ "name" : "{", "children" : []},
{ "name" : "Statement", "children" : [{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "println", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"key:value map size\"", "children" : []},
]},
{ "name" : "Name", "children" : [{ "name" : "i", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "SimpleStatement", "children" : [{ "name" : "PseudoCall", "children" : [{ "name" : "Name", "children" : [{ "name" : "panic", "children" : []},
]},
{ "name" : "(", "children" : []},
{ "name" : "ExpressionOrTypeList", "children" : [{ "name" : "Literal", "children" : [{ "name" : "\"fail\"", "children" : []},
]},
]},
{ "name" : "OComma", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : ")", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
{ "name" : "Empty ElseIfList", "children" : [{ "name" : "", "children" : []},
]},
{ "name" : "Else", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "Statement", "children" : [{ "name" : "", "children" : []},
]},
]},
{ "name" : "}", "children" : []},
]},
]},
]},
]},
]},
]},
][0];